services:
  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis:/data

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - '5432:5432'
    volumes:
      - docker-postgres:/var/lib/postgresql/data

volumes:
  redis:
    driver: local
  docker-postgres: